### ISSUE TITLE
User invitations

### ISSUE THREAD

**Issue by LukasKnuth** [LukasKnuth/Auther#14]
Instead of creating users directly (which forces an admin to choose secrets for them) we'll implement an invitation system.

## Features

* Create an invitation link
  * name and email _can_ be set
  * set the groups the user will belong to
* Links are only valid for a time (1 hour?)
* Clicking the link allows users to change pre-defined data and set password

## ToDo

- [ ] Create GenServer + ETS to store expiring data
- [ ] Create Controller for creating invitations (Secure this later!)
- [ ] Create Controller to consume a invitation link and set user-data
