### ISSUE TITLE
Implement User Accounts

### ISSUE THREAD

**Issue by LukasKnuth** [LukasKnuth/Auther#4]
Build everything needed to create/update/delete a User Account with Auther. Additionally, build 2FA using Time-Based One-Time-Passwords as a first-class member.

## ToDo

- [x] Context for creating/updating/deleting User
- [x] Helper to hash password securely
- [x] Controller for User login/logout and Session creation/destruction
- [x] Controller for updating user information
- [x] Controller for changing user password
- [ ] Controller for creating/deleting users (Secure this later!)
- [x] Middleware for checking for a user session
- [x] `authenticated` pipeline for actions requiring login

## Middleware

1. If Session-Cookie present, go to 3
2. Redirect to Login Page, give `original_url` as parameter for redirect after login
3. Take `user_id` from Session, query `User` from DB

**Comment by LukasKnuth** [comment]
The Point "Controller for creating/deleting users" will be replaced with #14 instead.
