### ISSUE TITLE
2FA using TOTP

### ISSUE THREAD

**Issue by LukasKnuth** [LukasKnuth/Auther#5]
Implement Two Factor Authentication using a Time-based One-Time-Password approach.

## ToDo

- [x] Context for enabling/disabling 2FA for a User
- [x] Helper to create/verify 2FA codes
- [ ] Context for using a 2FA fallback code for a User
- [ ] Context for re-rolling fallback codes for a User
- [ ] Controller for prompting user for 2FA code
- [ ] Controller for displaying fallback codes to user
- [ ] Middleware to ensure 2FA

## Prompt Controller implementation

1. If valid 2FA key given, redirect to `original_url`
2. If valid 2FA fallback key given, remove from `fallbacks` array
3. If `fallbacks` not empty, redirect to `original_url`
4. Re-roll fallbacks. Render fallback keys and link to `original_url`

## Middleware implementation

1. Load `last_interaction_time` from Session
2. If `last_interaction_time < X` minutes, continue to next Middleware
3. Redirect to 2FA prompt, add `original_url` as param (`X` depending on 2FA config)

**Comment by LukasKnuth** [comment]
Allow users to set something like "2FA Aggressiveness" to configure how often Auther will ask for a 2FA code. Options would be:

* `aggressive`: Ask after 5min of last usage
* `balanced`: Ask after 2h of last usage
* `required`: Ask only if operation requires 2FA to succeed

In general, 2FA would be used to "re-activate" a Session that has been IDLE for some time. This means that login session do not need to ever expire.
