### ISSUE TITLE
Groups for Users

### ISSUE THREAD

**Issue by LukasKnuth** [LukasKnuth/Auther#6]
Rights for both Auther and any consumable Services can be set by assigning Users to Groups which have OAuth Scopes attached to them.

## ToDo

- [ ] Context for creating/updating/deleting Groups
- [ ] Context for adding/removing User to/from Group
- [ ] Controller for creating/updating/deleting Groups
- [ ] Controller for adding/removing User to/from Group

**Comment by LukasKnuth** [comment]
It should be verified what can be used to find out which Scopes exist for Services. Maybe Services need to describe all valid Scopes in their configuration?

The format should be something like `<service>.<scope>`, e.g. `auther.create_group`.

An implicit, special `<service>.*` scope always exists which means "everything".

**Comment by LukasKnuth** [comment]
The previous Auther implementation already had Groups working. The Schema was defined as follows:

```elixir
schema "groups" do
  field :name, :string
  field :description, :string
  field :scopes, {:array, :string} # make sure these are all unique

  many_to_many :users, User, join_through: UserGroup

  timestamps()
end
```

The `join_through: UserGroup` stored a date with the association between user and group.

It also defined a context method for retrieving all unique scopes (from any group) that a user has access to:

```elixir
@spec get_scopes(user :: %User{}) :: MapSet.t(String.t())
def get_scopes(user) do
  user
  |> Repo.preload(:groups)
  |> Map.get(:groups, [])
  |> Enum.reduce(MapSet.new(), fn group, set ->
    Enum.reduce(group.scopes, set, &MapSet.put(&2, &1))
  end)
end
```
