### ISSUE TITLE
Password reset via email

### ISSUE THREAD

**Issue by LukasKnuth** [LukasKnuth/Auther#9]
Allow users to reset a lost password themselves.

## ToDo

- [ ] Helper to send emails
- [ ] Context to mark a User email as verified
- [ ] Change User update context to reset email verification if email is changed
- [ ] Controller to send User verification email
- [ ] Controller to accept User email verification link
- [ ] Helper to generate expiring password-reset links (maybe JWT tokens?)
- [ ] Controller to send User a password reset link
- [ ] Controller to change password via reset link

## Sending Emails

Maybe this can be done via the Domain hoster (cheap SMTP server with the Domain?). Otherwise, an external Service probably needs to be used, since sending emails without having them end up in "Spam" folders is hard.

## Email verification

It should be decided what can be done before the User has verified the email address. Possible options are:

1. Don't allow login at all until email verified
2. If email unverified and trying to restore, don't allow restoring (locked out)
3. Don't verify email at all, just send to address. If non-existing, bad luck
